---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        name: Set up golang 1.22
        with:
          go-version: '1.22.12'
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Gen private
        run: openssl genrsa -out private.pem 2048
      - name: Gen public
        run: openssl rsa -in private.pem -outform PEM -pubout -out public.pem
      - name: Run Tests
        run: go test
